import * as vscode from "vscode";
import {
  createPullRequest,
  detectGitHubRemote,
  getBranchInfo,
  getPrimerFilesFromStatus,
  commitAndPush
} from "../services.js";
import { getGitHubToken } from "../auth.js";
import { getWorkspacePath } from "./analyze.js";

export async function prCommand(): Promise<void> {
  const workspacePath = getWorkspacePath();
  if (!workspacePath) return;

  const remote = await detectGitHubRemote(workspacePath);
  if (!remote) {
    vscode.window.showErrorMessage("Primer: Could not detect a GitHub remote from origin.");
    return;
  }
  const { owner, repo } = remote;

  const branchInfo = await getBranchInfo(workspacePath);
  if (branchInfo.current === branchInfo.defaultBranch) {
    vscode.window.showErrorMessage(
      "Primer: Cannot create PR from the default branch. Check out a feature branch first."
    );
    return;
  }

  const title = await vscode.window.showInputBox({
    prompt: "Pull request title",
    value: `Add Primer AI configs for ${repo}`
  });
  if (!title) return;

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: "Primer: Creating pull request…" },
    async () => {
      try {
        const token = await getGitHubToken();

        const primerFiles = await getPrimerFilesFromStatus(workspacePath);

        if (primerFiles.length === 0) {
          vscode.window.showWarningMessage(
            "Primer: No Primer-generated files found. Run 'Primer: Initialize Repository' or 'Primer: Generate Configs' first."
          );
          return;
        }

        const picked = await vscode.window.showQuickPick(
          primerFiles.map((f) => ({ label: f, picked: true })),
          {
            canPickMany: true,
            placeHolder: "Select files to commit & push",
            title: "Primer: Confirm files"
          }
        );
        if (!picked || picked.length === 0) return;

        await commitAndPush(
          workspacePath,
          picked.map((p) => p.label),
          title,
          branchInfo.current,
          token
        );

        const prUrl = await createPullRequest({
          token,
          owner,
          repo,
          title,
          body: "Generated by Primer VS Code extension.",
          head: branchInfo.current,
          base: branchInfo.defaultBranch
        });

        const openAction = "Open in Browser";
        const action = await vscode.window.showInformationMessage(
          `Primer: Pull request created.`,
          openAction
        );
        if (action === openAction && prUrl.startsWith("https://")) {
          vscode.env.openExternal(vscode.Uri.parse(prUrl));
        }
      } catch (err) {
        vscode.window.showErrorMessage(
          `Primer: PR creation failed — ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }
  );
}
