import * as vscode from "vscode";
import { createPullRequest } from "../services.js";
import { getGitHubToken } from "../auth.js";
import { getWorkspacePath } from "./analyze.js";
import simpleGit from "simple-git";

export async function prCommand(): Promise<void> {
  const workspacePath = getWorkspacePath();
  if (!workspacePath) return;

  const git = simpleGit(workspacePath);

  // Detect remote owner/repo
  const remotes = await git.getRemotes(true);
  const origin = remotes.find((r) => r.name === "origin");
  if (!origin?.refs.push) {
    vscode.window.showErrorMessage("Primer: No origin remote found.");
    return;
  }

  const match = origin.refs.push.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
  if (!match) {
    vscode.window.showErrorMessage("Primer: Could not parse GitHub owner/repo from origin remote.");
    return;
  }
  const [, owner, repo] = match;

  const branch = (await git.branch()).current;
  const defaultBranch = await git
    .raw(["symbolic-ref", "refs/remotes/origin/HEAD", "--short"])
    .catch(() => "origin/main");
  const base = defaultBranch.replace("origin/", "").trim();

  if (branch === base) {
    vscode.window.showErrorMessage(
      "Primer: Cannot create PR from the default branch. Check out a feature branch first."
    );
    return;
  }

  const title = await vscode.window.showInputBox({
    prompt: "Pull request title",
    value: `Add Primer AI configs for ${repo}`
  });
  if (!title) return;

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: "Primer: Creating pull request…" },
    async () => {
      try {
        const token = await getGitHubToken();

        // Commit and push if there are changes
        const status = await git.status();
        if (status.files.length > 0) {
          const primerFiles = status.files
            .map((f) => f.path)
            .filter(
              (p) =>
                p.startsWith(".github/") ||
                p.startsWith(".vscode/") ||
                p.endsWith(".instructions.md") ||
                p === "primer.eval.json"
            );

          if (primerFiles.length === 0) {
            vscode.window.showWarningMessage("Primer: No Primer-generated files to commit.");
            return;
          }

          await git.add(primerFiles);
          await git.commit(title);
          await git.push("origin", branch);
        }

        const prUrl = await createPullRequest({
          token,
          owner: owner!,
          repo: repo!,
          title,
          body: "Generated by Primer VS Code extension.",
          head: branch,
          base
        });

        const openAction = "Open in Browser";
        const action = await vscode.window.showInformationMessage(
          `Primer: Pull request created.`,
          openAction
        );
        if (action === openAction && prUrl.startsWith("https://")) {
          vscode.env.openExternal(vscode.Uri.parse(prUrl));
        }
      } catch (err) {
        vscode.window.showErrorMessage(
          `Primer: PR creation failed — ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }
  );
}
