/** File patterns that Primer generates and should be included in PRs. */
export const PRIMER_FILE_PATTERNS = [
  ".github/copilot-instructions.md",
  ".vscode/mcp.json",
  ".vscode/settings.json",
  "AGENTS.md",
  "primer.eval.json"
] as const;

/** Check if a file path is a Primer-generated file. */
export function isPrimerFile(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, "/");
  return (
    PRIMER_FILE_PATTERNS.some((p) => normalized === p) || normalized.endsWith(".instructions.md")
  );
}

export function buildInstructionsPrBody(): string {
  return [
    "## 🤖 Copilot Instructions Added",
    "",
    "This PR adds a `.github/copilot-instructions.md` file to help GitHub Copilot understand this codebase better.",
    "",
    "### What's Included",
    "",
    "The instructions file contains:",
    "- Project overview and architecture",
    "- Tech stack and conventions",
    "- Build/test commands",
    "- Key directories and files",
    "",
    "### Benefits",
    "",
    "With these instructions, Copilot will:",
    "- Generate more contextually-aware code suggestions",
    "- Follow project-specific patterns and conventions",
    "- Understand the codebase structure",
    "",
    "---",
    "*Generated by [Primer](https://github.com/pierceboggan/primer) - Prime your repos for AI*"
  ].join("\n");
}

export function buildFullPrBody(): string {
  return [
    "## 🤖 Primed for AI",
    "",
    "This PR adds configurations to prime this repository for AI coding assistants.",
    "",
    "### Added Files",
    "",
    "| File | Purpose |",
    "|------|---------|",
    "| `.github/copilot-instructions.md` | Custom instructions for GitHub Copilot |",
    "| `.vscode/settings.json` | VS Code settings for optimal AI assistance |",
    "| `.vscode/mcp.json` | Model Context Protocol server configuration |",
    "",
    "### What's Included",
    "",
    "The instructions file contains:",
    "- Project overview and architecture",
    "- Tech stack and conventions",
    "- Build/test commands",
    "- Key directories and files",
    "",
    "### Benefits",
    "",
    "With these configurations, Copilot will:",
    "- Generate more contextually-aware code suggestions",
    "- Follow project-specific patterns and conventions",
    "- Understand the codebase structure",
    "- Have access to MCP tools for enhanced capabilities",
    "",
    "### How to Use",
    "",
    "1. Merge this PR",
    "2. Open the project in VS Code",
    "3. Start chatting with Copilot — it now understands your project!",
    "",
    "---",
    "*Generated by [Primer](https://github.com/pierceboggan/primer) - Prime your repos for AI*"
  ].join("\n");
}
